config/routes.rb
Gallery::Application.routes.draw do
  get "product/index"
  resources :comments

   resources :homes

  devise_for :users
  resources :supports
  resources :albums do 
    resources :photos
  end

  resources :photos, only: [:show, :edit] 

  root 'homes#index'

  

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/album.rb
class Album < ActiveRecord::Base
	#validates :title, presence: true
	belongs_to :user
	has_many :photos
	validates :title, presence: true
	#validate :title, (:presence=> true)	
	before_save :uppercase_title

	def uppercase_title
		self.title = self.title.capitalize
	end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_filter :authenticate_user! #, :except => [:show, :index]
  # load_and_authorize_resource
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  # before_filter :auth_user

  # def auth_user
  #   redirect_to new_user_session_url unless user_signed_in?
  # end

  # GET /albums
  # GET /albums.json
  def index
      # authorize! :read, @album
      @albums =  Album.find_all_by_user_id(current_user.id)
      #@albums = current_user.albums.load  This is the alternate way for it
      # @albums = Album.all
      # puts @albums
      # die
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
       # authorize! :read, @album
  end

  # GET /albums/new
  def new
    # @album = current_user.albums.build
     @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    # @album = Album.new
    # @album.user_id = current_user.id
    # @album.user = current_user
    @album = current_user.albums.build(album_params)
    # binding.pry
    respond_to do |format|
      if @album.save
      AlbumMailerWorker.perform_async(@album.id)
        #send email notifications 

        # AlbumMailer.notify_user(@album).deliver 
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album ||= Album.find(params[:id])
      # authorize! :read, @album
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, :html => {:multipart => true} do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<%= link_to 'Add Photos', new_album_photo_path(@album) %> |
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>